[deps]
BeliefPropagation = "f47dce41-c8ad-4b69-b8b4-f2a36c7ebdf8"
Documenter = "e30172f5-a6a5-5a46-863b-614d45cd2de4"
IndexedFactorGraphs = "edf0a622-c16b-410a-a162-e53dc16a76ae"

[compats]
Documenter = "1.0"
GraphRecipes = "0.5"
Plots = "1.39"
